In [1]:
using UncNLPTestSet, LinearAlgebra

┌ Info: Precompiling UncNLPTestSet [ac41c6d5-581c-4fd8-9896-caf0766f302e]
└ @ Base loading.jl:1342
┌ Warning: TODO: Debug BDQRTIC
└ @ UncNLPTestSet ~/.julia/dev/UncNLPTestSet/src/problems/BDQRTIC.jl:73
┌ Warning: TODO: Issue in CUTEst? See comment https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/blob/main/src/broydn7d.jl#L50 
└ @ UncNLPTestSet ~/.julia/dev/UncNLPTestSet/src/problems/BROYDN7D.jl:109
┌ Warning: TODO: Issue in CUTEst? See https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/blob/main/src/brybnd.jl
└ @ UncNLPTestSet ~/.julia/dev/UncNLPTestSet/src/problems/BRYBND.jl:110
┌ Warning: TODO: Debug CRAGGLVY
└ @ UncNLPTestSet ~/.julia/dev/UncNLPTestSet/src/problems/CRAGGLVY.jl:75
┌ Warning: TODO: Clean up DIXMAANB (and others) implementation. See comment block
└ @ UncNLPTestSet ~/.julia/dev/UncNLPTestSet/src/problems/DIXMAANB.jl:108
┌ Warning: TODO: Implement DIXON3DQ
└ @ UncNLPTestSet ~/.julia/dev/UncNLPTestSet/src/problems/DIXON3DQ.jl:1
┌ Warning: TOD

In [18]:
"""
    bfgs

```math
∇²f(x)
```
A variant of the Broyden-Fletcher-Goldfard-Shanno inverse Quasi-Newton update extended
to n-directions, such that the multi-secant equations are satisfied.

blah blah blah, list argument requitements here.
"""
function bfgs(H::Matrix{<:Real}, U::Matrix{<:Real}, V::Matrix{<:Real}, ϵ::Float64)
	 # requirement, and yeilds a differinent computation on pinv
	UTVᵀ = U*pinv(U'V, ϵ)*V'
	E = I - UTVᵀ
	return UTVᵀ + E*H*E
end

bfgs

In [3]:
nlp = SelectProgram("WOODS")
adjdim!(nlp, 500);

┌ Warning: adjdim!: This operation may be unstable
└ @ UncNLPTestSet /Users/daniel/.julia/dev/UncNLPTestSet/src/UncNLPTestSet.jl:185


In [39]:
S = rand(nlp.n, 8)
S = Matrix(qr(S).Q)

500×8 Matrix{Float64}:
 -0.0484034    -0.0219019   -0.0104649   …   0.0197457   -0.0102038
 -0.0322118    -0.0808963   -0.017994       -0.0190623   -0.0514474
 -0.0511354    -0.0588265   -0.00184697      0.0438097   -0.078449
 -0.0749262     0.0490627    0.0444998      -0.0467082   -0.00741938
 -0.00843064   -0.019104    -0.00729676      0.0709583    0.00924811
 -0.0691754    -0.0357342   -0.088676    …   0.0441329   -0.0256727
 -0.0454822    -0.00825969   0.0591846      -0.0588983    0.0509477
 -0.00145116   -0.0431031    0.0723346      -0.035613    -0.0503534
 -0.0522711    -0.0437662   -0.0739344      -0.0426949   -0.0290392
 -0.0759121     0.0662912   -0.0383603       0.0309447    0.019394
 -0.000780849  -0.102662     0.0648908   …   0.00290534  -0.0747688
 -0.0108455    -0.0987848   -0.0471467       0.0242376   -0.0468918
 -0.0767287     0.0332513    0.0128073       0.0123656   -0.0733059
  ⋮                                      ⋱               
 -0.0596539    -0.0155045    0.0224

In [5]:
V = gHS(nlp, nlp.x0, S, 16)

Y after first itr: columnns 4 rows 500
Y after 0.0625 itr: columnns 20 rows 500
Y after 1.0625 itr: columnns 36 rows 500
Y after 2.0625 itr: columnns 52 rows 500
Y after 3.0625 itr: columnns 68 rows 500
Y after 4.0625 itr: columnns 84 rows 500
Y after 5.0625 itr: columnns 100 rows 500
Y after 6.0625 itr: columnns 116 rows 500
Y after 7.0625 itr: columnns 132 rows 500
Y after 8.0625 itr: columnns 148 rows 500
Y after 9.0625 itr: columnns 164 rows 500
Y after 10.0625 itr: columnns 180 rows 500
Y after 11.0625 itr: columnns 196 rows 500
Y after 12.0625 itr: columnns 212 rows 500
Y after 13.0625 itr: columnns 228 rows 500
Y after 14.0625 itr: columnns 244 rows 500
Y after 15.0625 itr: columnns 260 rows 500
Y after 16.0625 itr: columnns 276 rows 500
Y after 17.0625 itr: columnns 292 rows 500
Y after 18.0625 itr: columnns 308 rows 500
Y after 19.0625 itr: columnns 324 rows 500
Y after 20.0625 itr: columnns 340 rows 500
Y after 21.0625 itr: columnns 356 rows 500
Y after 22.0625 itr: columnns 

500×500 Matrix{Float64}:
 -594.482     179.319    -184.565    …  -1673.19      351.059    -1.3701e8
  -67.2747     18.8023    -13.9672       -187.021      35.6171   -1.49048e7
  -51.6541    513.051     -55.5292        643.453     290.503    -1.10997e8
   -7.47458    60.5878     -1.00379        65.2202     30.1983   -1.20902e7
 -549.601     551.903    -399.027         269.512     391.793    -1.3701e8
  -63.434      59.1248    -41.4126   …     27.6115     41.4075   -1.49048e7
 -162.334     873.321     635.846        -687.817     301.395    -1.10997e8
  -21.5981     96.6366     71.8375        -76.2234     32.4992   -1.20902e7
  -47.1428    934.847    -319.035        -266.796    1262.83     -1.3701e8
   -8.03979   100.543     -29.4822        -27.4266    137.723    -1.49048e7
 -120.362     586.817    -136.473    …    270.517     155.484    -1.10997e8
  -15.1366     69.1878    -16.6559         27.7448     18.2391   -1.20902e7
 -664.619     -41.9973    359.904         -69.3471    346.225    -

In [6]:
H = hessAD(nlp, nlp.x0)

500×500 Matrix{Float64}:
 11202.0  1200.0      0.0     0.0  …      0.0     0.0      0.0     0.0
  1200.0   220.2      0.0    19.8         0.0     0.0      0.0     0.0
     0.0     0.0  10082.0  1080.0         0.0     0.0      0.0     0.0
     0.0    19.8   1080.0   200.2         0.0     0.0      0.0     0.0
     0.0     0.0      0.0     0.0         0.0     0.0      0.0     0.0
     0.0     0.0      0.0     0.0  …      0.0     0.0      0.0     0.0
     0.0     0.0      0.0     0.0         0.0     0.0      0.0     0.0
     0.0     0.0      0.0     0.0         0.0     0.0      0.0     0.0
     0.0     0.0      0.0     0.0         0.0     0.0      0.0     0.0
     0.0     0.0      0.0     0.0         0.0     0.0      0.0     0.0
     0.0     0.0      0.0     0.0  …      0.0     0.0      0.0     0.0
     0.0     0.0      0.0     0.0         0.0     0.0      0.0     0.0
     0.0     0.0      0.0     0.0         0.0     0.0      0.0     0.0
     ⋮                             ⋱                

In [25]:
H0 = I + zeros(500, 500)
H_qn = bfgs(H0, S, V, 10e-6)

500×500 Matrix{Float64}:
  1.0           5.42101e-19  -6.50521e-18  …   8.67362e-19   2.71051e-19
 -4.33681e-19   1.0          -7.58942e-19      6.50521e-19  -2.71051e-20
 -9.54098e-18   4.33681e-19   1.0             -1.73472e-18   0.0
 -7.58942e-19   1.6263e-19   -7.58942e-19      8.67362e-19   5.42101e-20
 -1.56125e-17  -6.50521e-19   4.33681e-18     -1.30104e-18  -4.87891e-19
  1.0842e-18   -4.06576e-20   2.1684e-19   …   6.50521e-19   4.06576e-20
 -3.46945e-18  -4.87891e-19   9.97466e-18      4.33681e-19  -5.42101e-20
  1.0842e-18    1.35525e-19  -1.0842e-19      -1.0842e-19   -5.42101e-20
  1.04083e-17  -3.25261e-19  -2.60209e-18      1.73472e-18   3.25261e-19
  1.6263e-18   -4.06576e-20   2.1684e-19      -1.0842e-19    1.35525e-20
 -3.46945e-18  -2.71051e-19   6.07153e-18  …  -8.67362e-19   5.42101e-20
  4.33681e-19  -2.71051e-20   9.75782e-19     -6.50521e-19  -2.71051e-20
 -1.73472e-18   1.0842e-19   -5.63785e-18      2.1684e-18    1.6263e-19
  ⋮                                

In [26]:
H_qn_s = bfgs(H0, S, V, 1e-6)

500×500 Matrix{Float64}:
  1.0           5.42101e-19  -6.50521e-18  …   8.67362e-19   2.71051e-19
 -4.33681e-19   1.0          -7.58942e-19      6.50521e-19  -2.71051e-20
 -9.54098e-18   4.33681e-19   1.0             -1.73472e-18   0.0
 -7.58942e-19   1.6263e-19   -7.58942e-19      8.67362e-19   5.42101e-20
 -1.56125e-17  -6.50521e-19   4.33681e-18     -1.30104e-18  -4.87891e-19
  1.0842e-18   -4.06576e-20   2.1684e-19   …   6.50521e-19   4.06576e-20
 -3.46945e-18  -4.87891e-19   9.97466e-18      4.33681e-19  -5.42101e-20
  1.0842e-18    1.35525e-19  -1.0842e-19      -1.0842e-19   -5.42101e-20
  1.04083e-17  -3.25261e-19  -2.60209e-18      1.73472e-18   3.25261e-19
  1.6263e-18   -4.06576e-20   2.1684e-19      -1.0842e-19    1.35525e-20
 -3.46945e-18  -2.71051e-19   6.07153e-18  …  -8.67362e-19   5.42101e-20
  4.33681e-19  -2.71051e-20   9.75782e-19     -6.50521e-19  -2.71051e-20
 -1.73472e-18   1.0842e-19   -5.63785e-18      2.1684e-18    1.6263e-19
  ⋮                                

In [28]:
H*S

500×500 Matrix{Float64}:
 -594.482     179.319    -184.565    …  -1673.19      351.059    -1.3701e8
  -67.2747     18.8023    -13.9672       -187.021      35.6171   -1.49048e7
  -51.6541    513.051     -55.5292        643.453     290.503    -1.10997e8
   -7.47458    60.5878     -1.00379        65.2202     30.1983   -1.20902e7
 -549.601     551.903    -399.027         269.512     391.793    -1.3701e8
  -63.434      59.1248    -41.4126   …     27.6115     41.4075   -1.49048e7
 -162.334     873.321     635.846        -687.817     301.395    -1.10997e8
  -21.5981     96.6366     71.8375        -76.2234     32.4992   -1.20902e7
  -47.1428    934.847    -319.035        -266.796    1262.83     -1.3701e8
   -8.03979   100.543     -29.4822        -27.4266    137.723    -1.49048e7
 -120.362     586.817    -136.473    …    270.517     155.484    -1.10997e8
  -15.1366     69.1878    -16.6559         27.7448     18.2391   -1.20902e7
 -664.619     -41.9973    359.904         -69.3471    346.225    -

In [31]:
function orth_proj(U::Matrix{<:Real}, V::Matrix{<:Real})
	return V - U*(U'*V)
end

orth_proj (generic function with 1 method)

In [33]:
S = orth_proj(S, V)

500×500 Matrix{Float64}:
 1.60268e13  -5.95277e12  -3.00844e12  …  -1.38695e12  4.35079e18
 2.77613e12  -1.03113e12  -5.21115e11     -2.40244e11  7.53635e17
 1.44252e13  -5.35789e12  -2.7078e12      -1.24834e12  3.916e18
 2.50919e12  -9.3198e11   -4.71008e11     -2.17144e11  6.8117e17
 1.60268e13  -5.95277e12  -3.00844e12     -1.38695e12  4.35079e18
 2.77613e12  -1.03113e12  -5.21115e11  …  -2.40244e11  7.53635e17
 1.44252e13  -5.35789e12  -2.7078e12      -1.24834e12  3.916e18
 2.50919e12  -9.3198e11   -4.71008e11     -2.17144e11  6.8117e17
 1.60268e13  -5.95277e12  -3.00844e12     -1.38695e12  4.35079e18
 2.77613e12  -1.03113e12  -5.21115e11     -2.40244e11  7.53635e17
 1.44252e13  -5.35789e12  -2.7078e12   …  -1.24834e12  3.916e18
 2.50919e12  -9.3198e11   -4.71008e11     -2.17144e11  6.8117e17
 1.60268e13  -5.95277e12  -3.00844e12     -1.38695e12  4.35079e18
 ⋮                                     ⋱               
 1.60268e13  -5.95277e12  -3.00844e12     -1.38695e12  4.35079e18
 2.7

In [34]:
S[:, 1]'*S[:, 2]

-2.2236679017962932e28

In [35]:
S * S

500×500 Matrix{Float64}:
 1.09173e31  -4.05496e30  -2.04931e30  …  -9.44771e29  2.96371e36
 1.89106e30  -7.02391e29  -3.54978e29     -1.63651e29  5.13367e35
 9.82625e30  -3.64973e30  -1.84452e30     -8.50357e29  2.66753e36
 1.70923e30  -6.34854e29  -3.20845e29     -1.47916e29  4.64005e35
 1.09173e31  -4.05496e30  -2.04931e30     -9.44771e29  2.96371e36
 1.89106e30  -7.02391e29  -3.54978e29  …  -1.63651e29  5.13367e35
 9.82625e30  -3.64973e30  -1.84452e30     -8.50357e29  2.66753e36
 1.70923e30  -6.34854e29  -3.20845e29     -1.47916e29  4.64005e35
 1.09173e31  -4.05496e30  -2.04931e30     -9.44771e29  2.96371e36
 1.89106e30  -7.02391e29  -3.54978e29     -1.63651e29  5.13367e35
 9.82625e30  -3.64973e30  -1.84452e30  …  -8.50357e29  2.66753e36
 1.70923e30  -6.34854e29  -3.20845e29     -1.47916e29  4.64005e35
 1.09173e31  -4.05496e30  -2.04931e30     -9.44771e29  2.96371e36
 ⋮                                     ⋱               
 1.09173e31  -4.05496e30  -2.04931e30     -9.44771e29  2.9637

500×500 Matrix{Float64}:
 11202.0          1200.0          …      1.04968e-14     3.00378e-15
  1200.0           220.2                 1.20125e-15     3.20365e-16
    -9.70118e-14     4.54801e-15        -1.65527e-14     5.85469e-17
    -1.04648e-14    19.8                -1.68698e-15     1.03162e-17
    -1.7359e-13     -7.33593e-15        -1.37937e-14    -5.41657e-15
    -1.84748e-14    -7.86895e-16  …     -1.42015e-15    -5.7759e-16
    -3.3808e-14     -4.77255e-15         4.25528e-15    -6.05093e-16
    -3.50848e-15    -5.00595e-16         4.5955e-16     -6.85948e-17
     1.18546e-13    -3.69236e-15         1.93023e-14     3.65983e-15
     1.28567e-14    -3.99802e-16         2.04491e-15     3.9276e-16
    -3.45106e-14    -2.76201e-15  …     -9.4473e-15      5.17273e-16
    -3.62798e-15    -2.98966e-16        -1.06913e-15     5.33888e-17
    -2.08635e-14     1.14947e-15         2.41604e-14     1.82178e-15
     ⋮                            ⋱                   
    -1.91722e-14    -6.17